spring:
  application:
    name: zapter-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/zapter
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time: 300000
    user:
      name: user
      password: pass
      roles: USER
razorpay:
    key-id: rzp_test_SYcy5fobkxRpqE
    key-secret: TlonLy6dF6qIIB5LgLF2sLS3
#